name: Deploy React App to AWS S3
on:
    push:
        branch:
            - main

# Define the runner for the job
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v1

            - name: Nodejs Setup
              uses: actions/setup-node@v1
              with:
                node-version: ${{ secrets.node_version }}
            
            - name: Install Dependencies
              run: npm install

            - name: Build the React App
              run: npm run build

            - name: Config AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
                aws-region: eu-north-1

            - name: Deploy to AWS S3 Bucket
              run: aws s3 sync build s3://myreactapp.cloud --delete